# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

import Tracker as Trk


class ComboBox(QtWidgets.QComboBox):
    popupAboutToBeShown = QtCore.pyqtSignal()

    def showPopup(self):
        self.popupAboutToBeShown.emit()
        super(ComboBox, self).showPopup()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 441)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 561, 271))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.DBTable = QtWidgets.QTableWidget(self.groupBox)
        self.DBTable.setGeometry(QtCore.QRect(10, 20, 541, 241))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DBTable.setFont(font)
        self.DBTable.setObjectName("DBTable")
        self.DBTable.setColumnCount(4)
        self.DBTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DBTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DBTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DBTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DBTable.setHorizontalHeaderItem(3, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 270, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.combobox = ComboBox(self.groupBox_2)
        self.combobox.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.combobox.setObjectName("combobox")
        self.combobox.addItem("")
        self.search = QtWidgets.QPushButton(self.groupBox_2)
        self.search.setGeometry(QtCore.QRect(252, 20, 39, 31))
        self.search.setObjectName("search")
        self.doexp = QtWidgets.QPushButton(self.groupBox_2)
        self.doexp.setGeometry(QtCore.QRect(10, 60, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.doexp.setFont(font)
        self.doexp.setObjectName("doexp")
        self.viewgraph = QtWidgets.QPushButton(self.groupBox_2)
        self.viewgraph.setGeometry(QtCore.QRect(105, 60, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.viewgraph.setFont(font)
        self.viewgraph.setObjectName("viewgraph")
        self.viewanal = QtWidgets.QPushButton(self.groupBox_2)
        self.viewanal.setGeometry(QtCore.QRect(200, 60, 92, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.viewanal.setFont(font)
        self.viewanal.setObjectName("viewanal")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 270, 261, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.LogMemo = QtWidgets.QTextEdit(self.groupBox_3)
        self.LogMemo.setGeometry(QtCore.QRect(10, 20, 241, 141))
        self.LogMemo.setObjectName("LogMemo")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 370, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.combobox.popupAboutToBeShown.connect(self.search_click)
        self.search.clicked.connect(self.searching)
        self.doexp.clicked.connect(Trk.doing_exp)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "DB구역"))
        item = self.DBTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X좌표"))
        item = self.DBTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y좌표"))
        item = self.DBTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "속도"))
        item = self.DBTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "각도"))
        self.DBTable.setColumnWidth(0, int(self.DBTable.width() * 1 / 5-1))
        self.DBTable.setColumnWidth(1, int(self.DBTable.width() * 1 / 5-1))
        self.DBTable.setColumnWidth(2, int(self.DBTable.width() * 1 / 5-1))
        self.DBTable.setColumnWidth(3, int(self.DBTable.width() * 1 / 5-1))
        self.DBTable.setColumnWidth(4, int(self.DBTable.width() * 1 / 5-1))
        self.groupBox_2.setTitle(_translate("MainWindow", "실험 도구"))
        self.combobox.setCurrentText(_translate("MainWindow", "ALL"))
        self.combobox.setItemText(0, _translate("MainWindow", "ALL"))
        self.search.setText(_translate("MainWindow", "검색"))
        self.doexp.setText(_translate("MainWindow", "실험 수행"))
        self.viewgraph.setText(_translate("MainWindow", "그래프 보기"))
        self.viewanal.setText(_translate("MainWindow", "통계 보기"))
        self.groupBox_3.setTitle(_translate("MainWindow", "로그[SQL쿼리]"))
        self.groupBox_4.setTitle(_translate("MainWindow", "정보"))

    def searching(self, event):
        self.DBTable.clearContents()
        if str(self.combobox.currentText()) == 'ALL':
            sql = "select * from experiment order by SECOND"
        else:
            sql = "select * from experiment where Exp_Name = '" + str(self.combobox.currentText()) + "' order by SECOND"
        print("select * from experiment where Exp_Name = '" + str(self.combobox.currentText()) + "' order by SECOND")
        Trk.cursor.execute(sql)
        row = Trk.cursor.fetchall()
        count = len(row)
        self.DBTable.setRowCount(count)
        for i in range(count):
            Name, sec, x, y, v, a, seta = row[i]
            self.DBTable.setVerticalHeaderItem(i, QTableWidgetItem(str(sec)))
            print(x)
            self.DBTable.setItem(i, 0, QTableWidgetItem(str(x)))
            self.DBTable.setItem(i, 1, QTableWidgetItem(str(y)))
            self.DBTable.setItem(i, 2, QTableWidgetItem(str(v)))
            self.DBTable.setItem(i, 3, QTableWidgetItem(str(a)))
            self.DBTable.setItem(i, 4, QTableWidgetItem(str(seta)))

    def search_click(self):
        self.combobox.clear()
        self.combobox.addItem('ALL')
        result = self.set_name()
        for record in result:
            self.combobox.addItem(record[0])

    @staticmethod
    def set_name():
        sql = "select distinct Exp_Name from experiment"
        Trk.cursor.execute(sql)
        result = Trk.cursor.fetchall()
        print(result)
        return result



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
